variables:
  DEBIAN_FRONTEND: noninteractive
  LC_ALL: C.UTF-8
  GIT_STRATEGY: fetch

stages:
  - configure
  - build
  - test
  - deploy

.debian_stretch: &debian_stretch
  image: cznic/debian:stretch-knot-latest
  tags:
    - docker
    - linux
    - amd64

.configure: &configure_job
  stage: configure
  script:
    - autoreconf -fi
    - ./configure --disable-fastparser
  artifacts:
    untracked: true
    expire_in: '1 hour'


configure:debian:stretch:amd64:
  <<: *debian_stretch
  <<: *configure_job

build:documentation:
  <<: *debian_stretch
  stage: build
  dependencies:
    - configure:debian:stretch:amd64
  only:
    - tags
    - triggers
    - doc-test
  script:
    - make -C doc html singlehtml pdf
  artifacts:
    paths:
      - doc/_build/html/
      - doc/_build/singlehtml/
      - doc/_build/latex/knot.pdf
    expire_in: '1 hour'

deploy:documentation:
  <<: *debian_stretch
  stage: deploy
  dependencies:
    - build:documentation
  only:
    - tags
    - triggers
    - doc-test
  script:
    - "curl --http1.1 --request POST --form token=$WEBSITE_TOKEN --form ref=master
      --form \"variables[RELEASE_CI_BUILD_REF_NAME]=$CI_COMMIT_REF_NAME\"
      --form \"variables[RELEASE_CI_BUILD_ID]=$CI_JOB_ID\"
      https://gitlab.labs.nic.cz/api/v3/projects/5/trigger/builds"
  artifacts:
    name: "knot-dns-$CI_COMMIT_REF_NAME-doc"
    paths:
      - doc/_build/html/
      - doc/_build/singlehtml/
      - doc/_build/latex/knot.pdf
